[package]
name = "weather-api"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.6"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
redis = { version = "0.25", features = ["tokio-comp", "aio"] }
shuttle-runtime = "0.35"
shuttle-axum = "0.35"
shuttle-secrets = "0.35"